### ISSUE TITLE
Use mailto with email addresses

### ISSUE THREAD

**Issue by reillysiemens** [kyle-rader/outinscience.com#13]
You could make it a little easier to contact people by making use email addresses a hyperlink of the form `mailto:user@domain.tld`.

**Comment by kyle-rader** [comment]
Agreed.

**Comment by kyle-rader** [comment]
You should PULL REQUEST!!

**Comment by reillysiemens** [comment]
That would require me to know Angular. I'm assuming I change [this line](https://github.com/kyle-rader/outinscience.com/blob/master/public/modules/the-out-list/views/templates/outlist-entry.client.view.template.html#L8)?

**Comment by kyle-rader** [comment]
Correct - Also Please make any pull requests to the dev branch. You would want to replace `{{user.email}}` with `<a href="mailto:{{user.email}}">{{user.email}}</a>`

**Comment by kyle-rader** [comment]
Moved to icons for email and phone.
