### ISSUE TITLE
Simple typos in glossary section

### ISSUE THREAD

**Issue by whoever1224** [kyle-rader/outinscience.com#26]
I did a quick proof-reading of the glossary section and found a few simple typos that are listed below. The original text is provided with errors and my comments in **bold**.

ASEXUAL: A term used to identify someone who does not experience sexual attraction to anyone. There are varying degrees of asexuality with titles such as grey-a and demisexual. A lack of sexual attraction does not necessarily mean an aversion to touch **or sex. as** there are often romantic attractions romantic relationships. It differs from celibacy, which refers to someone who experiences sexual attraction and chooses not to act on it.
**I think you meant for that period to be a comma.**

COMING OUT: It is the process by which **LGBT** individuals recognize, acknowledge, accept, and appreciate their sexual identity. It is commonly thought of as the act of telling the people in one's life about their identity which may be unknown to others. This may occur multiple times in different contexts (meeting someone new, work environment, social groups, family, etc.). Coming out can also be an internal process by which someone accepts themselves and their identity.
**Used LGBT instead of LGBTQ+, I’m not sure if that is intentional or not.**

GENDER ROLE: The accepted behaviors, thoughts, and emotions of a specific **Bender** based upon the views of a particular society or culture.
**I think you meant “gender” unless this is a very subtle Futurama reference.**

GSM/GSRM: Gender and Sexual Minority/Gender, Sexual, and Romantic Minority. An inclusive alternative to **LGBT** that includes all minority identities under the queer umbrella.
**Again used LGBT instead of LGBTQ+.**

HETEROSEXUAL PRIVILEGE: **he** benefits and advantages that heterosexuals receive in a heterosexist culture.
**I think you meant “The” but the ‘T’ got lost.**

HOMOSEXUAL
A person who has romantic and sexual feelings for or attractions to someone of the same gender. Historically, the term came from Dr Karoly Benkert (1869) to define "perversion" medically for gay/lesbian behavior and was once a diagnosis in the **<i>Diagnostic and Statistical Manual of Mental Disorders</i>** (Version III).
**Uh oh, HTML hiccup. Github is displaying it correctly but in the glossary the formatting is showing**

INTERNALIZED **HONOPHOBIA:**
**Should be INTERNALIZED HOMOPHOBIA**

LAMBDA: A symbol originally chosen by the Gay Activists Alliance of New York in 1970 and used to identify other members of the gay community. The reasoning was that the symbol would easily be mistaken for a fraternity symbol and therefore ignored by the majority of people. In December of 1974, the lambda was officially declared the international symbol for gay and lesbian rights by the **international Fay Rights** Congress in Edinburgh, Scotland.
**I think you meant “International Gay Rights” there.**

TRANSSEXUAL: A transgender person who chose to undergo gender affirming surgery **gender (reassignment surgery).**
**Should read “gender affirming surgery (gender reassignment surgery).” Open paren in wrong place.**

**Comment by kyle-rader** [comment]
Thank you @whoever1224  for the edits!  They are now live. https://github.com/kyle-rader/outinscience.com/commit/9673f0dd825f0cb3a6e9df305a45a8af41567f15?diff=unified
